// Generated by gencpp from file tractor_gps/states_rtkRequest.msg
// DO NOT EDIT!


#ifndef TRACTOR_GPS_MESSAGE_STATES_RTKREQUEST_H
#define TRACTOR_GPS_MESSAGE_STATES_RTKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tractor_gps
{
template <class ContainerAllocator>
struct states_rtkRequest_
{
  typedef states_rtkRequest_<ContainerAllocator> Type;

  states_rtkRequest_()
    {
    }
  states_rtkRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tractor_gps::states_rtkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tractor_gps::states_rtkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct states_rtkRequest_

typedef ::tractor_gps::states_rtkRequest_<std::allocator<void> > states_rtkRequest;

typedef boost::shared_ptr< ::tractor_gps::states_rtkRequest > states_rtkRequestPtr;
typedef boost::shared_ptr< ::tractor_gps::states_rtkRequest const> states_rtkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tractor_gps::states_rtkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace tractor_gps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tractor_gps::states_rtkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tractor_gps::states_rtkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tractor_gps::states_rtkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tractor_gps::states_rtkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tractor_gps/states_rtkRequest";
  }

  static const char* value(const ::tractor_gps::states_rtkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::tractor_gps::states_rtkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct states_rtkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tractor_gps::states_rtkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tractor_gps::states_rtkRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TRACTOR_GPS_MESSAGE_STATES_RTKREQUEST_H
