// Generated by gencpp from file tractor_gps/states_rtk.msg
// DO NOT EDIT!


#ifndef TRACTOR_GPS_MESSAGE_STATES_RTK_H
#define TRACTOR_GPS_MESSAGE_STATES_RTK_H

#include <ros/service_traits.h>


#include <tractor_gps/states_rtkRequest.h>
#include <tractor_gps/states_rtkResponse.h>


namespace tractor_gps
{

struct states_rtk
{

typedef states_rtkRequest Request;
typedef states_rtkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct states_rtk
} // namespace tractor_gps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tractor_gps::states_rtk > {
  static const char* value()
  {
    return "f2b37e695a8f10e8df0555b3b2850dbe";
  }

  static const char* value(const ::tractor_gps::states_rtk&) { return value(); }
};

template<>
struct DataType< ::tractor_gps::states_rtk > {
  static const char* value()
  {
    return "tractor_gps/states_rtk";
  }

  static const char* value(const ::tractor_gps::states_rtk&) { return value(); }
};


// service_traits::MD5Sum< ::tractor_gps::states_rtkRequest> should match
// service_traits::MD5Sum< ::tractor_gps::states_rtk >
template<>
struct MD5Sum< ::tractor_gps::states_rtkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tractor_gps::states_rtk >::value();
  }
  static const char* value(const ::tractor_gps::states_rtkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tractor_gps::states_rtkRequest> should match
// service_traits::DataType< ::tractor_gps::states_rtk >
template<>
struct DataType< ::tractor_gps::states_rtkRequest>
{
  static const char* value()
  {
    return DataType< ::tractor_gps::states_rtk >::value();
  }
  static const char* value(const ::tractor_gps::states_rtkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tractor_gps::states_rtkResponse> should match
// service_traits::MD5Sum< ::tractor_gps::states_rtk >
template<>
struct MD5Sum< ::tractor_gps::states_rtkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tractor_gps::states_rtk >::value();
  }
  static const char* value(const ::tractor_gps::states_rtkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tractor_gps::states_rtkResponse> should match
// service_traits::DataType< ::tractor_gps::states_rtk >
template<>
struct DataType< ::tractor_gps::states_rtkResponse>
{
  static const char* value()
  {
    return DataType< ::tractor_gps::states_rtk >::value();
  }
  static const char* value(const ::tractor_gps::states_rtkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRACTOR_GPS_MESSAGE_STATES_RTK_H
