// Generated by gencpp from file tractor_controller/state_tractor.msg
// DO NOT EDIT!


#ifndef TRACTOR_CONTROLLER_MESSAGE_STATE_TRACTOR_H
#define TRACTOR_CONTROLLER_MESSAGE_STATE_TRACTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tractor_controller
{
template <class ContainerAllocator>
struct state_tractor_
{
  typedef state_tractor_<ContainerAllocator> Type;

  state_tractor_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , v(0.0)  {
    }
  state_tractor_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , v(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::tractor_controller::state_tractor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tractor_controller::state_tractor_<ContainerAllocator> const> ConstPtr;

}; // struct state_tractor_

typedef ::tractor_controller::state_tractor_<std::allocator<void> > state_tractor;

typedef boost::shared_ptr< ::tractor_controller::state_tractor > state_tractorPtr;
typedef boost::shared_ptr< ::tractor_controller::state_tractor const> state_tractorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tractor_controller::state_tractor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tractor_controller::state_tractor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tractor_controller::state_tractor_<ContainerAllocator1> & lhs, const ::tractor_controller::state_tractor_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.v == rhs.v;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tractor_controller::state_tractor_<ContainerAllocator1> & lhs, const ::tractor_controller::state_tractor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tractor_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tractor_controller::state_tractor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tractor_controller::state_tractor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tractor_controller::state_tractor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tractor_controller::state_tractor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tractor_controller::state_tractor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tractor_controller::state_tractor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tractor_controller::state_tractor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d02065475d2208fe262b04f47261a35";
  }

  static const char* value(const ::tractor_controller::state_tractor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d02065475d2208fULL;
  static const uint64_t static_value2 = 0xe262b04f47261a35ULL;
};

template<class ContainerAllocator>
struct DataType< ::tractor_controller::state_tractor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tractor_controller/state_tractor";
  }

  static const char* value(const ::tractor_controller::state_tractor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tractor_controller::state_tractor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 yaw\n"
"float64 v\n"
;
  }

  static const char* value(const ::tractor_controller::state_tractor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tractor_controller::state_tractor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_tractor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tractor_controller::state_tractor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tractor_controller::state_tractor_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACTOR_CONTROLLER_MESSAGE_STATE_TRACTOR_H
