# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
 #Position Controller-----------------------------------
left_steer_joint:
  type:  effort_controllers/JointPositionController
  joint: left_steering_joint
  pid: {p: 10, i: 0.00, d: 1}
right_steer_joint:
  type:  effort_controllers/JointPositionController
  joint: right_steering_joint
  pid: {p: 10, i: 0.00, d: 1}

#left_steer_joint:
#  type:  tractor_controller/JointSteerController
#  joint: left_steering_joint
#  pid: {p: 3.0, i: 0.00, d: 0.001}
#right_steer_joint:
#  type:  tractor_controller/JointSteerController
#  joint: right_steering_joint
#  pid: {p: 3.0, i: 0.00, d: 0.001}