gazebo_ros_control:
  pid_gains:
    left_steering_joint:
      p: 1
      i: 0
      d: 0
    right_steering_joint:
      p: 1
      i: 0
      d: 0
    left_rear_axle:
      p: 1
      i: 0
      d: 0
    right_rear_axle:
      p: 1
      i: 0
      d: 0
    left_front_axle:
      p: 1
      i: 0
      d: 0
    right_front_axle:
      p: 1
      i: 0
      d: 0

    
